web/apps/users/urls.py
from django.urls import include, path

from ..users import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('utils/', include('apps.users.utils.urls')),
]

web/apps/users/utils/urls.py
from django.urls import path

from . import utils

app_name = 'utils'
urlpatterns = [
    path('check_username/', utils.check_username, name='check_username'),
    path('check_email/', utils.check_email, name='check_email')
]

web/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.core.core_urls')),
                  path('users/', include('apps.users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/apps/users/models.py
import uuid

from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser, PermissionsMixin):
    """
    Attributes:
        uuid: The UUID of the user. Primary key.
        username: The username of the user. From AbstractUser.
        date_joined: The date the user joined. From AbstractUser.
        is_active: Whether the user is active. From AbstractUser.

    """
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, db_index=True)
    email = models.EmailField(verbose_name=_('email address'), unique=True)

    USERNAME_FIELD = 'uuid'
    REQUIRED_FIELDS = ['username', 'email']

    def __str__(self):
        return self.username

    def __repr__(self):
        return f'<CustomUser uuid={self.uuid} username={self.username}>'

web/apps/users/forms.py
from typing import override

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .exceptions import AuthenticationException
from .repository import UserRepository
from .services import UserService

user_service = UserService(UserRepository())

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if '@' in username:
            raise forms.ValidationError('Username should not contain "@"')

        return super().clean_username()

    @override
    def save(self, commit=True):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password1')

        user: User = user_service.register_user(username=username, email=email, password=password)
        return user


class CustomAuthenticationForm(forms.Form):
    username_or_email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username_or_email = self.cleaned_data.get('username_or_email')
        password = self.cleaned_data.get('password')

        if username_or_email is None or password is None:
            raise forms.ValidationError('Empty username or password')

        try:
            user: User = user_service.authenticate_user(username_or_email, password)
        except AuthenticationException as exception:
            raise forms.ValidationError(exception.message)
        else:
            self.cleaned_data['user'] = user

        return self.cleaned_data

    def get_user(self) -> User:
        return self.cleaned_data.get('user')

web/apps/users/views.py
from typing import override

from django.contrib.auth import get_user_model, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, RedirectView

from .forms import CustomAuthenticationForm, CustomUserCreationForm

User = get_user_model()

SHOP_LIST_URL = reverse_lazy('core:shops:list')


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/register.html'
    success_url = SHOP_LIST_URL

    @override
    def get_success_url(self) -> str:
        return self.success_url

    @override
    def form_valid(self, form: CustomUserCreationForm) -> HttpResponseRedirect:
        user: User = form.save()
        login(request=self.request, user=user)
        return HttpResponseRedirect(self.get_success_url())


class LoginView(FormView):
    form_class = CustomAuthenticationForm
    template_name = 'users/login.html'
    success_url = SHOP_LIST_URL

    @override
    def get_success_url(self) -> str:
        return self.success_url

    @override
    def form_valid(self, form: CustomAuthenticationForm) -> HttpResponseRedirect:
        user: User = form.get_user()
        login(request=self.request, user=user)
        return HttpResponseRedirect(self.get_success_url())


class LogoutView(RedirectView):
    url = SHOP_LIST_URL

    @override
    def get_redirect_url(self, *args, **kwargs) -> str:
        logout(request=self.request)
        return super().get_redirect_url(*args, **kwargs)

web/apps/users/templates/users/login.html
{% extends "users/extend_base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5 shadow">
                    <div class="card-header bg-success text-white">
                        <h3 class="mb-0 text-center"><i class="bi bi-person-fill me-2"></i>Login</h3>
                    </div>
                    <div class="card-body">
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                                <i class="bi bi-exclamation-circle me-2"></i>
                                {% for error in form.non_field_errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.username_or_email.id_for_label }}">Username/Email</label>
                                <input type="text" class="form-control" id="{{ form.username_or_email.id_for_label }}"
                                       name="{{ form.username_or_email.html_name }}" required
                                       autocomplete="username|email">
                            </div>
                            <div class="form-group">
                                <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                                <input type="password" class="form-control"
                                       id="{{ form.password.id_for_label }}"
                                       name="{{ form.password.html_name }}" required autocomplete="current-password">
                            </div>
                            <button type="submit" class="btn btn-success w-100 mt-4 mb-3">Login</button>
                            <a href="{% url 'users:signup' %}" class="btn btn-link">Don't have an account? Register</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

web/apps/users/templates/users/register.html
{% extends "users/extend_base.html" %}
{% load static %}

{% block title %}Register{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5 shadow">
                    <div class="card-header bg-success text-white">
                        <h3 class="mb-0 text-center"><i class="bi bi-person-plus-fill me-2"></i>Register</h3>
                    </div>
                    <div class="card-body">
                        <form id="register-form" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.username.id_for_label }}"><i class="bi bi-person-fill me-2"></i>Username</label>
                                <input type="text" class="form-control" id="{{ form.username.id_for_label }}"
                                       name="{{ form.username.html_name }}" required autocomplete="username">
                                <div id={{ form.username.id_for_label }}-feedback></div>
                            </div>
                            <div class="form-group">
                                <label for="{{ form.email.id_for_label }}"><i class="bi bi-envelope-fill me-2"></i>Email</label>
                                <input type="email" class="form-control" id="{{ form.email.id_for_label }}"
                                       name="{{ form.email.html_name }}" required autocomplete="email">
                                <div id={{ form.email.id_for_label }}-feedback></div>
                            </div>
                            <div class="form-group">
                                <label for="{{ form.password1.id_for_label }}">Password</label>
                                <input type="password" class="form-control" id="{{ form.password1.id_for_label }}"
                                       name="{{ form.password1.html_name }}" required autocomplete="new-password">

                            </div>
                            <div class="form-group">
                                <label for="{{ form.password2.id_for_label }}">Confirm
                                    Password</label>
                                <input type="password" class="form-control"
                                       id="{{ form.password2.id_for_label }}"
                                       name="{{ form.password2.html_name }}" required autocomplete="new-password">
                            </div>
                            <button id="register-button" type="submit"
                                    class="btn btn-success w-100 mt-4 mb-3">
                                Register
                            </button>
                            <a href="{% url 'users:login' %}" class="btn btn-link">Already have an account? Login</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
    <script>

        const usernameInput = document.getElementById('{{ form.username.id_for_label }}');
        const usernameFeedback = document.getElementById('{{ form.username.id_for_label }}-feedback');

        const emailInput = document.getElementById('{{ form.email.id_for_label }}');
        const emailFeedback = document.getElementById('{{ form.email.id_for_label }}-feedback');

        const registerButton = document.getElementById('register-button');

        checkFieldAvailability(usernameInput, usernameFeedback, '{% url "users:utils:check_username" %}');
        checkFieldAvailability(emailInput, emailFeedback, '{% url "users:utils:check_email" %}');


        /**
         * Функция debounce для ограничения частоты вызова функции.
         *
         * @param {Function} func - Функция, вызов которой нужно ограничить.
         * @param {number} wait - Задержка в миллисекундах между вызовами функции.
         * @returns {Function} - Возвращает новую функцию, которую можно вызывать с ограниченной частотой.
         */
        function debounce(func, wait) {
            let timeout;
            return function (...args) {
                // Сохраняем контекст вызова функции
                const context = this;
                // Очищаем предыдущий таймаут
                clearTimeout(timeout);
                // Устанавливаем новый таймаут с вызовом функции
                timeout = setTimeout(() => func.apply(context, args), wait);
            };
        }

        /**
         * Функция для проверки доступности поля (имя пользователя или email) на сервере.
         *
         * @param {HTMLElement} input - Элемент ввода, который нужно проверить.
         * @param {HTMLElement} feedback - Элемент, в который выводится обратная связь для пользователя.
         * @param {string} url - URL-адрес сервера для проверки доступности.
         * @param {number} delay - Задержка в миллисекундах между вызовами функции (по умолчанию 500).
         */
        function checkFieldAvailability(input, feedback, url, delay = 500) {

            const debouncedCheckAvailability = debounce(() => {
                const value = input.value.trim();
                if (value === '' || (input.type === 'email' && !value.includes('@'))) {
                    feedback.innerHTML = '';
                    return;
                }

                fetch(`${url}?value=${value}`)
                    .then(response => response.json())
                    .then(data => {
                        feedback.innerHTML = '';
                        const alert = document.createElement('div');
                        alert.classList.add(data.is_available ? 'text-success' : 'text-danger');
                        alert.textContent = `This ${input.name} is ${data.is_available ? 'available' : 'already taken'}`;
                        feedback.appendChild(alert);
                    })
                    .catch(console.error);
            }, delay);

            input.addEventListener('input', debouncedCheckAvailability);
        }


    </script>
{% endblock extra_js %}