web/apps/users/urls.py
from django.urls import include, path

from ..users import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('utils/', include('apps.users.utils.urls')),
]

web/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.core.core_urls')),
                  path('users/', include('apps.users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/apps/core/models.py
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Shop(models.Model):
    """
    Represents an online store.

    Attributes:
        id (int): The unique identifier of the store.
        title (str): The stores name.
        description (str): Description of the store.
        imageUrl (str): URL of the stores image.
        search_vector (SearchVectorField): The search vector for the store.
    """
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    imageUrl = models.URLField(verbose_name=_('Image URL'))
    # Search vector for full-text search in the title and description fields.
    search_vector = SearchVectorField(null=True)

    class Meta:
        indexes = [GinIndex(fields=['search_vector'])]
        verbose_name = _('Shop')
        verbose_name_plural = _('Shops')

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'<Shop id={self.pk}, title={self.title}>'

    def get_absolute_url(self):
        return reverse('core:shops:detail', kwargs={'pk': self.pk})


class Product(models.Model):
    """
    Represents a product in an online store.

    Attributes:
        id (int): The unique identifier of the product.
        description (str): The description of the product.
        title (str): The name of the product.
        amount (int): The number of products in stock.
        price (float): The price of the product.
        active (bool): Whether the product is available for purchase.
        shop (Shop): The store in which the product is sold.
    """
    description = models.TextField(verbose_name=_('Description'))
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    amount = models.IntegerField(verbose_name=_('Amount'))
    price = models.FloatField(verbose_name=_('Price'))
    images = models.JSONField(default=list, verbose_name=_('Images'))
    active = models.BooleanField(default=True, verbose_name=_('Active'))
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='products', verbose_name=_('Shop'))

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'<Product id={self.pk}, title={self.title}>'


class Category(models.Model):
    """
    Represents a category of products in an online store.

    Attributes:
        id (int): The unique identifier of the category.
        title (str): The name of the category.
        description (str): Description of the category.
        parent (Category): The parent category of the category.
        products (list[Product]): The products in the category.
    """
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children',
                               verbose_name=_('Parent category'))
    products = models.ManyToManyField(Product, related_name='categories', verbose_name=_('Products'))

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'<Category id={self.pk}, title={self.title}>'

web/apps/core/forms/shop_forms.py
from django import forms

from ..fields import DescriptionTextareaWidget, ImagePreviewWidget, ImageUrlPreviewField, TitleInputWidget
from ..models import Shop
from ..repositories.shop_repositories import ShopRepository
from ..services.shop_services import ShopService
from ..types import URL

shop_service = ShopService(ShopRepository())


class CreateShopForm(forms.ModelForm):
    image = ImageUrlPreviewField(required=False)

    class Meta:
        model = Shop
        fields = ['title', 'description', 'image']
        widgets = {
            'title': TitleInputWidget(),
            'description': DescriptionTextareaWidget(),
            'image': ImagePreviewWidget()
        }

    def create_shop(self):
        title: str = self.cleaned_data.get('title')
        description: str = self.cleaned_data.get('description')
        image_url: URL = self.cleaned_data.get('image')

        shop = shop_service.create_shop(
            title=title,
            description=description,
            image_url=image_url
        )

        return shop

web/apps/core/views/shop_views.py
from typing import override

from django.http import HttpResponseRedirect
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView

from ..forms.shop_forms import CreateShopForm
from ..models import Shop
from ..repositories.shop_repositories import ShopRepository
from ..services.shop_services import ShopService

# Dependency Injection of ShopService 🤣😆
shop_service = ShopService(ShopRepository())


class ShopListView(ListView):
    model = Shop
    template_name = 'core/shop/shop_list.html'

    @override
    def get_queryset(self):
        if 'search' in self.request.GET:
            return shop_service.search_shops_by_title(self.request.GET['search'])

        return shop_service.get_all_shops()


class ShopSearchView(ListView):
    pass


class ShopDetailView(View):
    pass


class ShopUpdateView(UpdateView):
    pass


class ShopCreateView(CreateView):
    form_class = CreateShopForm
    template_name = 'core/shop/shop_create.html'

    @override
    def form_valid(self, form: CreateShopForm):
        shop = form.create_shop()
        return HttpResponseRedirect(shop.get_absolute_url())

web/templates/core/includes/footer.html
<p class="text-center">Made with ❤️, several cups of ☕ (coffee) and a couple of 🌙 (sleepless nights) in <span
        id="currentYear"></span>.</p>

<script>
    document.getElementById('currentYear').textContent = String(new Date().getFullYear());
</script>

web/templates/core/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:shops:list' %}">
            <img src="{% static 'core/img/logo.png' %}" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Shops</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Products</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>